kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  namespace: chat-app
  labels:
    app: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/db
