apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful
  namespace: sql
spec:
  selector:
    matchLabels:
      app: sql 
  serviceName: mysql-service
  replicas: 2  
  template:
    metadata:
      labels:
        app: sql 
    spec:
      containers:
      - name: sql
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          valueFrom:
            ConfigMapKeyRef:
              name: mysql-config-map
              key: MYSQL_DATABASE
          volumeMounts:
        - name: mysql_data
          mountPath: c/Users/Admin/Desktop/Yash/K8s/mysql 
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
